# Generated by Django 3.2.7 on 2021-10-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_auto_20211013_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('imai', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('landline1', models.CharField(max_length=200)),
                ('landline2', models.CharField(blank=True, max_length=200, null=True)),
                ('gstin', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=13)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=20)),
                ('maritial_status', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=200)),
                ('arname', models.CharField(max_length=200)),
                ('arno', models.CharField(max_length=200)),
                ('arrelation', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=13)),
                ('aadhar', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('aadharno', models.CharField(max_length=12)),
                ('contact', models.CharField(max_length=13)),
                ('hos_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('imai', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('aadharno', models.CharField(max_length=12)),
                ('contact', models.CharField(max_length=13)),
                ('hos_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('imai', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=13)),
                ('hos_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital')),
            ],
        ),
    ]
