# Generated by Django 3.2.7 on 2021-11-29 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0017_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital', serialize=False, to='auth.user')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Only numeric characters of length 6 is allowed')])),
                ('city', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('state', models.CharField(max_length=127)),
                ('web', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient', serialize=False, to='auth.user')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=1)),
                ('occupation', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('emergency_contact_name', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('emergency_contact_relation', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Only numeric characters of length 6 is allowed')])),
                ('city', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('state', models.CharField(max_length=127)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital_staff', serialize=False, to='auth.user')),
                ('role', models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse'), ('S', 'Staff'), ('O', 'Other')], max_length=1)),
                ('degree', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('department', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('designation', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('hos_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainAccessOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.patient')),
                ('secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital')),
            ],
            options={
                'unique_together': {('primary', 'secondary')},
            },
        ),
        migrations.CreateModel(
            name='BlockchainAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_actors', to='user_details.patient')),
                ('secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_actors', to='user_details.hospital')),
            ],
            options={
                'unique_together': {('primary', 'secondary')},
            },
        ),
    ]
