# Generated by Django 3.2.7 on 2021-10-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20211013_1138'),
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=12)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=13)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hos_code',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hos_code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='hospital',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_details.employee'),
        ),
    ]
