# Generated by Django 3.2.7 on 2021-10-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='mobile',
        ),
        migrations.AddField(
            model_name='doctor',
            name='aadharno',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bed_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doi',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='aremail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='degree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.CharField(max_length=13),
        ),
    ]
