# Generated by Django 3.2.7 on 2021-10-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20211013_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.employee'),
        ),
    ]
