# Generated by Django 3.2.7 on 2021-10-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20211018_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='aadharno',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bed_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='aremail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(),
        ),
    ]
