# Generated by Django 3.2.7 on 2021-11-02 14:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_auto_20211018_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
