# Generated by Django 3.2.7 on 2021-10-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20211013_1138'),
        ('user_details', '0003_alter_hospital_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('imai', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('imai', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('aadharno', models.CharField(max_length=12)),
                ('contact', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('aadharno', models.CharField(max_length=12)),
                ('contact', models.CharField(max_length=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='staff',
            name='hos_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='hos_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hos_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital'),
        ),
    ]
