# Generated by Django 3.2.7 on 2021-10-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_auto_20211013_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hos_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='hos_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hos_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital'),
        ),
    ]
