# Generated by Django 3.2.7 on 2021-11-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='maritial_status',
            new_name='martial_status',
        ),
    ]
