# Generated by Django 3.2.7 on 2021-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_rename_maritial_status_patient_martial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='martial_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=1),
        ),
    ]
