# Generated by Django 3.2.7 on 2021-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0007_alter_patient_martial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(max_length=127),
        ),
    ]
