# Generated by Django 3.2.7 on 2021-11-02 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0008_alter_patient_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('[a-zA-Z]', 'Only alphabets are allowed')]),
        ),
    ]
