# Generated by Django 3.2.7 on 2021-11-02 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0011_alter_patient_arname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='aremail',
            new_name='emergency_contact_email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='arname',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='arno',
            new_name='emergency_contact_phone',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='arrelation',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed')]),
        ),
    ]
