# Generated by Django 3.2.7 on 2021-11-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0012_auto_20211102_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='arrelation',
            new_name='emergency_contact_relation',
        ),
    ]
