# Generated by Django 3.2.7 on 2021-11-02 16:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0014_alter_patient_emergency_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
