# Generated by Django 3.2.7 on 2021-11-02 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0015_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
    ]
