# Generated by Django 3.2.7 on 2021-11-02 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0016_auto_20211102_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='aadhar',
            new_name='aadhaar',
        ),
        migrations.AlterField(
            model_name='patient',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Only numeric characters of length 6 is allowed')]),
        ),
    ]
