# Generated by Django 3.2.7 on 2021-11-02 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0017_auto_20211102_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhaar',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$', 'Invalid regex')]),
        ),
    ]
