# Generated by Django 3.2.7 on 2021-11-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0018_alter_patient_aadhaar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pin_code',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aadhaar',
        ),
    ]
