# Generated by Django 3.2.7 on 2021-11-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0019_auto_20211102_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='martial_status',
            new_name='marital_status',
        ),
    ]
