# Generated by Django 3.2.7 on 2021-11-03 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0020_rename_martial_status_patient_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Only numeric characters of length 6 is allowed')]),
        ),
    ]
