# Generated by Django 3.2.7 on 2021-11-03 09:19

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0021_alter_patient_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Only numeric characters of length 6 is allowed')]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
    ]
