# Generated by Django 3.2.7 on 2021-11-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0022_auto_20211103_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='pin_code',
            new_name='zip_code',
        ),
    ]
