# Generated by Django 3.2.7 on 2021-11-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0023_rename_pin_code_hospital_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='landline2',
            new_name='landline',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='landline1',
        ),
    ]
