# Generated by Django 3.2.7 on 2021-11-03 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0024_auto_20211103_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='bed_count',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='imai',
        ),
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')]),
        ),
    ]
