# Generated by Django 3.2.7 on 2021-11-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0025_auto_20211103_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='landline',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
