# Generated by Django 3.2.7 on 2021-11-04 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_auto_20211018_0007'),
        ('user_details', '0027_auto_20211103_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse'), ('S', 'Staff'), ('O', 'Other')], max_length=1)),
                ('degree', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('department', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('designation', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets are allowed')])),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('hos_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital')),
            ],
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hos_code',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hos_code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
