# Generated by Django 3.2.7 on 2021-11-06 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_details', '0028_auto_20211104_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital_staff', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
