# Generated by Django 3.2.7 on 2021-11-09 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0030_auto_20211109_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Only numeric characters of max length 6 is allowed')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Only numeric characters of max length 6 is allowed')]),
        ),
    ]
