# Generated by Django 3.2.7 on 2021-11-09 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0032_auto_20211109_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{4,9}$', 'Only numeric characters in the range of 5 to 9 is allowed')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{4,9}$', 'Only numeric characters in the range of 5 to 9 is allowed')]),
        ),
    ]
