# Generated by Django 3.2.7 on 2021-11-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0033_auto_20211109_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_profile'),
        ),
    ]
