# Generated by Django 3.2.7 on 2021-11-11 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0034_hospital_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Only numeric characters of length 6 is allowed')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Only numeric characters of length 6 is allowed')]),
        ),
    ]
