# Generated by Django 3.2.7 on 2021-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0035_auto_20211111_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_hash', models.CharField(max_length=128)),
                ('secondary_hash', models.CharField(max_length=128)),
            ],
        ),
    ]
