# Generated by Django 3.2.7 on 2021-11-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0036_blockchainaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockchainaccess',
            unique_together={('primary_hash', 'secondary_hash')},
        ),
    ]
