# Generated by Django 3.2.7 on 2021-11-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0037_alter_blockchainaccess_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockchainAccess',
        ),
    ]
