# Generated by Django 3.2.7 on 2021-11-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0038_delete_blockchainaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_actors', to='user_details.patient')),
                ('secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_actors', to='user_details.patient')),
            ],
            options={
                'unique_together': {('primary', 'secondary')},
            },
        ),
    ]
