# Generated by Django 3.2.7 on 2021-11-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0039_blockchainaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainaccess',
            name='secondary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_actors', to='user_details.hospital'),
        ),
    ]
