# Generated by Django 3.2.7 on 2021-11-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0040_alter_blockchainaccess_secondary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAccessOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.patient')),
                ('secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.hospital')),
            ],
            options={
                'unique_together': {('primary', 'secondary')},
            },
        ),
    ]
